Repository Traewelling/traewelling, pull requests merged in 2021-06, with the labels that each got.

#383 🚑️ Fixed Leaderboard data and performance
  app/Http/Controllers/API/UserController.php
  app/Http/Controllers/API/v1/StatisticsController.php
  app/Http/Controllers/Backend/LeaderboardController.php
  resources/views/leaderboard/includes/main-table.blade.php
  resources/views/leaderboard/month.blade.php
Labels: ready for review

#392 🐛 Fix time formatting
  resources/views/stats/includes/global_cards.blade.php
Labels: ready for review

#394 🐛 Prevent users from muting themselves
  app/Http/Controllers/Backend/UserController.php
  app/Http/Controllers/Frontend/UserController.php
  resources/views/includes/mute-button.blade.php
  resources/views/profile.blade.php
Labels: ready for review

#395 🚸 Link current commit to repo
  resources/views/layouts/app.blade.php
Labels: ready for review

#396 🚸 [AdminPanel] Show all events
  app/Http/Controllers/Backend/Admin/TelegramController.php
  app/Http/Controllers/Frontend/Admin/EventController.php
  resources/views/admin/events/list.blade.php
Labels: ready for review

#397 🚸 [AdminPanel] Improved charts
  app/Http/Controllers/Backend/Admin/DashboardController.php
  app/Http/Controllers/Frontend/Admin/DashboardController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/TransportController.php
  resources/views/admin/charts/hafasPolylines.blade.php
  resources/views/admin/charts/statusesByDate.blade.php
  resources/views/admin/charts/transportTypes.blade.php
  resources/views/admin/charts/userRegistration.blade.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/usageboard.blade.php
  resources/views/stats/includes/chart_categories.blade.php
  resources/views/stats/includes/chart_companies.blade.php
  resources/views/stats/includes/chart_volume.blade.php
  routes/web/admin.php
Labels: ready for review

#412 ⚡️ Improved performance of notifications
  app/Http/Controllers/NotificationController.php
  app/Models/User.php
  app/Notifications/UserJoinedConnection.php
  tests/Feature/NotificationsTest.php
Labels: ready for review

#413 ⚡️ Improved session performance
  database/migrations/2021_06_08_200223_add_index_to_sessions_table.php
Labels: ready for review

#414 ⚡️ Improved dashboard performance
  app/Http/Controllers/StatusController.php
Labels: ready for review

#415 ⚡️ Improved profile performance
  app/Http/Controllers/UserController.php
Labels: ready for review

#416 ⚡️ Improved check-in performance
  app/Http/Controllers/TransportController.php
Labels: ready for review

#405 🚸 Force user to reload styles and scripts if needed
  public/mix-manifest.json
  resources/views/layouts/app.blade.php
  webpack.mix.js
Labels: ready for review

#393 🚸 Hide past events without check-ins
  app/Http/Controllers/Frontend/EventController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/SitemapController.php
Labels: ready for review

#401 ✨ Vue can now log in to the api, fave posts and also delete their own!
  .idea/php.xml
  .idea/trwl.iml
  app/Http/Controllers/API/AuthController.php
  app/Http/Controllers/API/ResponseController.php
  app/Http/Controllers/API/StatusController.php
  app/Http/Controllers/API/v1/AuthController.php
  app/Http/Controllers/API/v1/LikesController.php
  app/Http/Controllers/API/v1/StatisticsController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/API/v1/UserController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/StatusController.php
  app/Http/Kernel.php
  app/Http/Middleware/SemiGuest.php
  app/Http/Resources/LeaderboardUserResource.php
  app/Http/Resources/StatusResource.php
  app/Models/Status.php
  composer.json
  composer.lock
  config/cors.php
  package-lock.json
  package.json
  public/mix-manifest.json
  resources/components/Dashboard.vue
  resources/components/LeaderboardTable.vue
  resources/components/Login.vue
  resources/components/ModalConfirm.vue
  resources/components/Status.vue
  resources/js/APImodels.js
  resources/js/vue.js
  resources/routes.js
  resources/views/ActiveStatuses.vue
  resources/views/App.vue
  resources/views/Event.vue
  resources/views/Leaderboard.vue
  resources/views/LeaderboardMonth.vue
  resources/views/Profile.vue
  resources/views/SingleStatus.vue
  resources/views/landing.blade.php
  routes/api.php
  tests/Feature/ApiStatusTest.php
Labels: APIv1

#436 🗃️ Replaced polyline hash by id
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/Backend/GeoController.php
  app/Http/Controllers/HafasController.php
  app/Http/Controllers/StatusController.php
  app/Models/HafasTrip.php
  app/Models/PolyLine.php
  app/Models/TrainCheckin.php
  database/factories/HafasTripFactory.php
  database/migrations/2020_09_28_170005_add_foreign_keys_to_hafas_trips.php
  database/migrations/2021_06_14_100826_add_polyline_id_to_hafas_trips.php
  database/migrations/2021_06_14_103257_remove_polyline_hash_from_hafas_trips.php
  resources/views/activejourneys.blade.php
  tests/Feature/DistanceCalculationTest.php
Labels: ready for review

#442 🚑 Allow invalidation & recreation of mastodon secrets
  app/Http/Controllers/SocialController.php
  app/Models/User.php
Labels: bug

#443 Vue again!
  .idea/inspectionProfiles/Project_Default.xml
  app/Http/Controllers/API/StatusController.php
  app/Http/Controllers/API/v1/AuthController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/StatusController.php
  app/Http/Controllers/TransportController.php
  app/Http/Resources/UserSettingsResource.php
  database/migrations/2021_06_14_103257_remove_polyline_hash_from_hafas_trips.php
  package-lock.json
  package.json
  resources/components/CheckInModal.vue
  resources/components/FADropdown.vue
  resources/components/Status.vue
  resources/js/APImodels.js
  resources/js/translations.js
  resources/js/vue.js
  resources/views/App.vue
  resources/views/Stationboard.vue
  resources/views/Trip.vue
  routes/api.php
Labels: ready for review
