Repository Traewelling/traewelling, pull requests merged in 2021-11, with the labels that each got.

#583 🥅 Add a timeout error to HAFAS API and return errors correctly
  .env.testing
  app/Http/Controllers/API/ResponseController.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/AuthController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/API/v1/UserController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/HafasController.php
  config/trwl.php
  tests/Feature/ApiCheckinTest.php
  tests/Feature/CheckinTest.php
  tests/TestCase.php
Labels: ready for review

#516 ✨ Add interface for the ticket system
  .env.example
  app/Http/Controllers/Backend/Support/TicketController.php
  app/Http/Controllers/Frontend/Support/SupportController.php
  config/ticket.php
  resources/lang/de.json
  resources/lang/en.json
  resources/views/layouts/app.blade.php
  resources/views/support/form.blade.php
  routes/web.php
Labels: ready for review

#599 🎨 Improve type safety in models
  app/Models/Event.php
  app/Models/EventSuggestion.php
  app/Models/Follow.php
  app/Models/FollowRequest.php
  app/Models/HafasTrip.php
  app/Models/IcsToken.php
  app/Models/Like.php
  app/Models/MastodonServer.php
  app/Models/PolyLine.php
  app/Models/PrivacyAgreement.php
  app/Models/SocialLoginProfile.php
  app/Models/Status.php
  app/Models/TrainCheckin.php
  app/Models/TrainStation.php
  app/Models/TrainStopover.php
  app/Models/User.php
  app/Models/UserMute.php
  phpcs.xml
Labels: ready for review

#601 🐛 Fix unexpected 404 with Vue and Laravels routes
  app/Http/Controllers/API/v1/TransportController.php
  resources/components/StationForm.vue
  resources/components/views/Stationboard.vue
Labels: bug, Vue

#596 ✨💥 Add login functionality with either username or email
  app/Http/Controllers/API/AuthController.php
  app/Http/Controllers/API/v1/AuthController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Backend/Auth/LoginController.php
  resources/components/Login.vue
  resources/lang/de.json
  resources/lang/en.json
  resources/views/auth/login.blade.php
Labels: APIv0, do not merge, APIv1, ready for review

#597 🗃️ Add unique key to TrainCheckin
  app/Exceptions/TrainCheckinAlreadyExistException.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/TransportController.php
  database/migrations/2021_11_03_211948_add_unique_key_to_train_checkins.php
Labels: do not merge, database, ready for review

#609 🩹 Hide email and tel if missing
  resources/views/legal/notice.blade.php
Labels: ready for review, small change

#612 🩹 Fix responsive table
  resources/views/events/overview.blade.php
Labels: ui, ready for review, small change

#613 🚸 Hide private users on leaderboard
  app/Http/Controllers/Backend/LeaderboardController.php
Labels: ready for review, small change

#614 🚚 Prepare profile url to match beta
  app/Http/Controllers/FrontendUserController.php
  app/Http/Controllers/SitemapController.php
  app/Notifications/FollowRequestApproved.php
  app/Notifications/UserFollowed.php
  resources/views/includes/messages/checkin-success.blade.php
  resources/views/includes/status.blade.php
  resources/views/layouts/app.blade.php
  resources/views/leaderboard/includes/main-table.blade.php
  resources/views/leaderboard/month.blade.php
  resources/views/profile.blade.php
  resources/views/search.blade.php
  resources/views/settings/follower.blade.php
  routes/web.php
  tests/Feature/MutedProfileVisibilityTest.php
  tests/Feature/PrivateProfileFollowerRelationsTest.php
  tests/Feature/PrivateProfileVisibilityTest.php
  tests/Feature/StaticPagesThatMightHaveComputedPropertiesTest.php
Labels: ready for review, small change

#611 🚸 Make event attributes nullable
  app/Models/Event.php
  database/migrations/2021_11_06_193343_make_url_nullable_at_events.php
  resources/views/events/overview.blade.php
  resources/views/eventsMap.blade.php
Labels: ready for review, small change

#602 ✨ Better Animation in Vue
  resources/components/Spinner.vue
Labels: Vue

#605 🎨 Move most axios requests to separate Javascript Class
  app/Http/Controllers/API/v1/IcsController.php
  app/Http/Controllers/API/v1/TransportController.php
  resources/components/CheckInModal.vue
  resources/components/FollowButton.vue
  resources/components/MuteButton.vue
  resources/components/Notification.vue
  resources/components/NotificationsModal.vue
  resources/components/Settings/AccountSettings.vue
  resources/components/Settings/ConnectivitySettings.vue
  resources/components/Settings/ProfileSettings.vue
  resources/components/StationForm.vue
  resources/components/Status.vue
  resources/components/layouts/NavbarComponent.vue
  resources/components/views/ActiveStatuses.vue
  resources/components/views/Dashboard.vue
  resources/components/views/Event.vue
  resources/components/views/Leaderboard.vue
  resources/components/views/LeaderboardMonth.vue
  resources/components/views/Profile.vue
  resources/components/views/SearchView.vue
  resources/components/views/Settings.vue
  resources/components/views/SingleStatus.vue
  resources/components/views/Stationboard.vue
  resources/components/views/Statistics.vue
  resources/components/views/Trip.vue
  resources/js/ApiClient/Checkin.js
  resources/js/ApiClient/Dashboard.js
  resources/js/ApiClient/Event.js
  resources/js/ApiClient/Helpers.js
  resources/js/ApiClient/Notifications.js
  resources/js/ApiClient/Settings.js
  resources/js/ApiClient/Statistics.js
  resources/js/ApiClient/Status.js
  resources/js/ApiClient/User.js
  resources/js/routes.js
  resources/js/vue.js
  resources/lang/de.json
  resources/lang/en.json
Labels: APIv1, ready for review, Vue

#610 🌐 Improve translations
  resources/lang/de.json
  resources/lang/en.json
Labels: ready for review, small change

#618 ⬆️ Update dependencies and require security advisories
  composer.json
  composer.lock
  package-lock.json
Labels: ready for review, small change

#598 🧹🔥 Sort structure to frontend/backend, remove deprecated code
  app/Http/Controllers/API/StatusController.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Helper/PrivacyHelper.php
  app/Http/Controllers/Backend/IcsController.php
  app/Http/Controllers/Backend/NotificationController.php
  app/Http/Controllers/Backend/SettingsController.php
  app/Http/Controllers/Backend/Social/MastodonController.php
  app/Http/Controllers/Backend/Social/TwitterController.php
  app/Http/Controllers/Backend/StatisticController.php
  app/Http/Controllers/Backend/Transport/HomeController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/Backend/User/DashboardController.php
  app/Http/Controllers/Backend/User/SessionController.php
  app/Http/Controllers/Backend/User/TokenController.php
  app/Http/Controllers/Backend/UserController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/HafasController.php
  app/Http/Controllers/StatusController.php
  app/Http/Controllers/TransportController.php
  resources/views/includes/edit-modal.blade.php
  tests/Feature/ApiUserTest.php
Labels: ready for review

#622 ✨ Update Vue maps to display geoJSON
  resources/components/Map.vue
  resources/components/views/ActiveStatuses.vue
Labels: ready for review, Vue

#625 ✅ Test with PHP 8.1
  .github/workflows/phpunit.yml
  app/Http/Controllers/NotificationController.php
  composer.lock
Labels: ready for review, small change

#628 ⬆️ Drop unsupported node versions
  .github/workflows/nodejs-dev.yml
  .github/workflows/nodejs-prod.yml
Labels: ready for review, small change

#621 ✨ Modify the checkin flow to give more insights about points and the ability to force checkin
  app/Enum/PointReasons.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Transport/PointsCalculationController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/TransportController.php
  app/Http/Resources/AdditionalPointsResource.php
  app/Http/Resources/PointsCalculationResource.php
  resources/components/CheckInModal.vue
  resources/components/CheckinSuccessModal.vue
  resources/components/ModalConfirm.vue
  resources/components/layouts/Basic.vue
  resources/components/views/Dashboard.vue
  resources/js/routes.js
  resources/js/vue.js
  resources/lang/de.json
  resources/lang/de_by.json
  resources/lang/de_he.json
  resources/lang/de_pfl.json
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/nb_NO.json
  resources/lang/nl.json
  resources/lang/pl.json
  resources/lang/sv.json
  tests/Feature/Transport/PointsCalculation/ReasonTest.php
  tests/Unit/Transport/PointsCalculation/FactorTest.php
  tests/Unit/TransportControllerTest.php
Labels: APIv1, ready for review, Vue

#634 ⬆️ Upgrade dependencies
  .idea/php.xml
  .idea/trwl.iml
  composer.json
  composer.lock
Labels: ready for review, small change

#635 🐛 Fix namespace
  tests/Unit/Transport/PointsCalculation/FactorTest.php
Labels: ready for review, small change

#608 🚸 Improve station search
  app/Helpers/Helper.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Transport/StationController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/HafasController.php
  app/Http/Controllers/TransportController.php
  resources/views/activejourneys.blade.php
  resources/views/events/overview.blade.php
  resources/views/eventsMap.blade.php
  resources/views/includes/station-autocomplete.blade.php
  resources/views/includes/status.blade.php
  resources/views/stationboard.blade.php
  tests/Feature/CheckinTest.php
  tests/Feature/NotificationsTest.php
  tests/Feature/StationSearchTest.php
  tests/TestCase.php
  tests/Unit/HelperMethodTest.php
Labels: ready for review

#633 🐛 Improve UserJoinedNotification and fix data bug
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/TransportController.php
  app/Notifications/UserJoinedConnection.php
  resources/views/includes/notification.blade.php
Labels: ready for review
