Repository Traewelling/traewelling, pull requests merged in 2021-10, with the labels that each got.

#531 🔥 Simplify message blocks
  resources/views/includes/message-block.blade.php
Labels: ready for review

#528 🌐 Add validation translations
  resources/lang/de/auth.php
  resources/lang/de/pagination.php
  resources/lang/de/passwords.php
  resources/lang/de/validation-attributes.php
  resources/lang/de/validation-inline.php
  resources/lang/de/validation.php
  resources/lang/en/auth.php
  resources/lang/en/pagination.php
  resources/lang/en/passwords.php
  resources/lang/en/validation-attributes.php
  resources/lang/en/validation-inline.php
  resources/lang/en/validation.php
  resources/lang/fr/auth.php
  resources/lang/fr/pagination.php
  resources/lang/fr/passwords.php
  resources/lang/fr/validation-attributes.php
  resources/lang/fr/validation-inline.php
  resources/lang/fr/validation.php
  resources/lang/nl/auth.php
  resources/lang/nl/pagination.php
  resources/lang/nl/passwords.php
  resources/lang/nl/validation-attributes.php
  resources/lang/nl/validation-inline.php
  resources/lang/nl/validation.php
  resources/lang/pl/auth.php
  resources/lang/pl/pagination.php
  resources/lang/pl/passwords.php
  resources/lang/pl/validation-inline.php
  resources/lang/pl/validation.php
  resources/lang/sv/auth.php
  resources/lang/sv/pagination.php
  resources/lang/sv/passwords.php
  resources/lang/sv/validation-inline.php
  resources/lang/sv/validation.php
Labels: ready for review

#529 🚸 Add divider to stationboard
  resources/lang/de.json
  resources/lang/en.json
  resources/sass/app.scss
  resources/sass/components/stationboard.scss
  resources/views/stationboard.blade.php
Labels: ui, ready for review

#530 🐛🚸 Fix permissions and improve message block
  app/Models/Status.php
  resources/lang/de.json
  resources/lang/de_by.json
  resources/lang/de_he.json
  resources/lang/de_pfl.json
  resources/lang/en.json
  resources/views/includes/message-block.blade.php
  resources/views/includes/messages/checkin-success.blade.php
Labels: ready for review

#540 🔥 Remove stub
  app/Http/Controllers/SocialController.php
  routes/web.php
Labels: ready for review

#543 🗃️ Add foreign key to social login profiles
  database/migrations/2021_10_08_160350_add_foreign_key_to_social_login_profiles.php
Labels: ready for review

#585 🚀 Docker image for easier deployment
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
  app/Providers/AppServiceProvider.php
  docker-entrypoint.sh
Labels: enhancement

#592 🚑️ Fix export data
  app/Http/Controllers/Backend/Export/ExportController.php
Labels: ready for review

#588 🐛 Fix exports if just one day is given
  app/Http/Controllers/Backend/Export/ExportController.php
Labels: ready for review

#589 🐛 Fix distance on exports
  app/Http/Controllers/Backend/Export/Format/CsvExportController.php
  resources/views/pdf/export-template.blade.php
Labels: ready for review

#590 🐛 Fix train number on exports
  app/Http/Controllers/Backend/Export/Format/CsvExportController.php
  resources/views/pdf/export-template.blade.php
Labels: ready for review

#591 🐛 Fix dropdown
  resources/views/export.blade.php
Labels: ui, ready for review
