Repository Traewelling/traewelling, pull requests merged in 2022-02, with the labels that each got.

#699 :bug: Fix GDPR Middleware
  app/Http/Middleware/PrivacyInterceptionMiddleware.php
  tests/Feature/ApiAuthTest.php
Labels: ready for review

#675 🎨 Remove Code duplication in UserResources
  app/Http/Resources/UserBaseResource.php
  app/Http/Resources/UserResource.php
  app/Http/Resources/UserSettingsResource.php
Labels: APIv1, ready for review

#700 :bug: Suppress exception
  app/Exceptions/Handler.php
Labels: ready for review

#619 🔒️ Improve model permissions handling
  app/Http/Controllers/API/StatusController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/StatusController.php
  app/Http/Controllers/TransportController.php
  app/Http/Controllers/UserController.php
  app/Http/Resources/UserBaseResource.php
  app/Models/Follow.php
  app/Models/Status.php
  app/Models/TrainCheckin.php
  app/Models/User.php
  app/Policies/StatusPolicy.php
  app/Policies/UserPolicy.php
  app/Providers/AuthServiceProvider.php
  database/factories/FollowFactory.php
  database/factories/HafasTripFactory.php
  database/factories/StatusFactory.php
  database/factories/TrainCheckinFactory.php
  database/factories/UserFactory.php
  resources/views/includes/messages/checkin-success.blade.php
  resources/views/profile.blade.php
  tests/Feature/NotificationsTest.php
  tests/Feature/Privacy/Status/ViewTest.php
  tests/Feature/PrivateProfileFollowerRelationsTest.php
  tests/TestCase.php
Labels: ready for review

#626 ✨ Drop PHP 8.0, implement Enums
  .github/workflows/phpunit.yml
  .idea/php.xml
  .idea/trwl.iml
  README.md
  app/Enum/BasicEnum.php
  app/Enum/Business.php
  app/Enum/HafasTravelType.php
  app/Enum/PointReason.php
  app/Enum/PointReasons.php
  app/Enum/StatusVisibility.php
  app/Enum/TravelType.php
  app/Http/Controllers/API/AuthController.php
  app/Http/Controllers/API/StatusController.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/SettingsController.php
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Export/Format/CsvExportController.php
  app/Http/Controllers/Backend/Transport/PointsCalculationController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/Backend/User/DashboardController.php
  app/Http/Controllers/Frontend/SettingsController.php
  app/Http/Controllers/Frontend/StatisticController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/HafasController.php
  app/Http/Controllers/StatusController.php
  app/Http/Controllers/TransportController.php
  app/Http/Controllers/UserController.php
  app/Http/Resources/HafasTripResource.php
  app/Http/Resources/PointsCalculationResource.php
  app/Http/Resources/StatisticsTravelPurposeResource.php
  app/Http/Resources/StatusResource.php
  app/Models/HafasTrip.php
  app/Models/Status.php
  app/Models/User.php
  app/Policies/StatusPolicy.php
  composer.lock
  database/factories/HafasTripFactory.php
  database/factories/StatusFactory.php
  database/factories/UserFactory.php
  database/migrations/2021_07_24_124933_create_default_visibility_on_users.php
  database/seeders/TrainCheckinSeeder.php
  resources/views/about.blade.php
  resources/views/includes/status.blade.php
  resources/views/includes/visibility-dropdown.blade.php
  resources/views/pdf/export-template.blade.php
  resources/views/settings/cards/privacy.blade.php
  resources/views/trip.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/CheckinTest.php
  tests/Feature/Privacy/Status/ViewTest.php
  tests/Feature/Transport/PointsCalculation/ReasonTest.php
  tests/TestCase.php
  tests/Unit/Transport/PointsCalculation/FactorTest.php
  tests/Unit/TransportControllerTest.php
Labels: php, ready for review

#709 :construction_worker: Improve codacy workflows
  .github/workflows/codacy-analysis.yml
  .github/workflows/phpunit.yml
Labels: postreview required

#708 :arrow_up: Upgrade to Laravel 9
  .idea/php.xml
  .idea/trwl.iml
  app/Http/Middleware/TrustProxies.php
  composer.json
  composer.lock
  config/filesystems.php
Labels: postreview required

#723 💥 ✨ add legal notice to vue (change names in .env)
  .env.example
  config/app.php
  resources/components/layouts/FooterComponent.vue
  resources/components/layouts/SidebarNavContent.vue
  resources/components/views/LegalNotice.vue
  resources/js/routes.js
Labels: breaking change, postreview required
