Repository Traewelling/traewelling, pull requests merged in 2022-04, with the labels that each got.

#801 :sparkles: Add remarks
  app/Http/Controllers/HafasController.php
  app/Models/HafasTrip.php
  app/Models/Remark.php
  database/factories/RemarkFactory.php
  database/migrations/2022_04_02_000000_create_remarks_table.php
  database/migrations/2022_04_02_000001_create_trip_remarks_table.php
  tests/Feature/Transport/RemarkTest.php
Labels: postreview required

#800 :children_crossing: Improve search
  app/Http/Controllers/UserController.php
  routes/web.php
Labels: postreview required

#789 :fire: Remove deprecated checkin function
  .env.testing
  .github/workflows/nodejs-dev.yml
  .github/workflows/nodejs-prod.yml
  .github/workflows/phpunit.yml
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/Frontend/Admin/CheckinController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/HafasController.php
  app/Http/Controllers/TransportController.php
  composer.json
  composer.lock
  config/trwl.php
  database/factories/HafasTripFactory.php
  database/migrations/2022_03_29_000000_add_index_to_train_stopovers.php
  database/migrations/2022_04_02_000000_change_unique_key_to_support_multiple_stopovers_per_station.php
  database/seeders/HafasTripSeeder.php
  database/seeders/TrainCheckinSeeder.php
  routes/api.php
  tests/Feature/ApiCheckinTest.php
  tests/Feature/CheckinTest.php
  tests/Feature/DistanceCalculationTest.php
  tests/TestCase.php
Labels: postreview required

#802 :bug: Fix distance calculation for ring lines
  app/Http/Controllers/Backend/GeoController.php
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/StatusController.php
  tests/Feature/CheckinTest.php
Labels: postreview required

#803 :sparkles: Add DS100 to station autocomplete
  app/Http/Controllers/FrontendTransportController.php
  app/Http/Controllers/TransportController.php
  resources/js/components/station-autocomplete.js
  resources/views/includes/station-autocomplete.blade.php
Labels: postreview required

#804 :sparkles: Add maintenance page
  resources/lang/de.json
  resources/lang/en.json
  resources/views/errors/503.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/minimal.blade.php
  storage/framework/maintenance.php
Labels: postreview required

#806 :bug: Improve status map
  app/Http/Controllers/API/v1/StatusController.php
  app/Http/Controllers/Backend/GeoController.php
  app/Http/Controllers/FrontendStatusController.php
  app/Http/Controllers/StatusController.php
  app/Models/TrainCheckin.php
  resources/views/includes/status.blade.php
Labels: postreview required

#807 :art: Improve ui
  resources/views/dashboard.blade.php
Labels: small change, postreview required

#809 :bug: Improve code
  app/Http/Controllers/Backend/EventController.php
  app/Http/Controllers/StatusController.php
  app/Http/Kernel.php
  routes/api.php
Labels: small change

#820 :bug: Fix wrong strikeout of platforms
  app/Http/Resources/StopoverResource.php
  app/Models/TrainStopover.php
  resources/components/views/Trip.vue
Labels: APIv1, Vue

#826 :bug: Fix apilogs table
  database/migrations/2022_04_07_085923_change_status_code_datatype_in_api_logs_table.php
Labels: small change

#827 🚑 Catch unset stations in distance calculation progress
  app/Http/Controllers/Backend/GeoController.php
Labels: postreview required

#831 :fix: Fix checkin via admin dashboard
  app/Http/Controllers/Frontend/Admin/CheckinController.php
Labels: postreview required

#833 :bug: Fix ics generator
  app/Http/Controllers/Backend/IcsController.php
Labels: postreview required

#837 :bug: Catch pdo exception while saving remarks
  app/Http/Controllers/HafasController.php
Labels: postreview required

#838 :bug: Catch pdo exception while saving train stopovers
  app/Http/Controllers/HafasController.php
Labels: postreview required

#842 :bug: Catch AlreadyCheckInException
  app/Exceptions/Checkin/AlreadyCheckedInException.php
  app/Http/Controllers/API/TransportController.php
  app/Http/Controllers/API/v1/TransportController.php
  app/Http/Controllers/Backend/Transport/TrainCheckinController.php
  app/Http/Controllers/Frontend/Admin/CheckinController.php
  app/Http/Controllers/FrontendTransportController.php
  resources/lang/de.json
  resources/lang/en.json
Labels: postreview required

#847 :zap: Improve queries
  app/Http/Controllers/HafasController.php
Labels: postreview required

#848 :zap: Improve queries
  app/Http/Controllers/HafasController.php
Labels: postreview required
