Repository Traewelling/traewelling, pull requests merged in 2023-12, with the labels that each got.

#2202 :lipstick: Make export column select a little larger
  resources/views/export.blade.php
Labels: ui

#2226 :technologist: add migration script for stopovers
  database/migrations/2023_12_20_000000_migrate_stopover_relation_id_in_train_checkins.php
Labels: do not merge

#2177 🌐 add frontend translations to vue components
  .gitignore
  lang/ca.json
  lang/cs.json
  lang/de.json
  lang/de/auth.php
  lang/de/pagination.php
  lang/de/passwords.php
  lang/de/validation-inline.php
  lang/de/validation.php
  lang/de_by.json
  lang/de_he.json
  lang/de_pfl.json
  lang/en.json
  lang/en/auth.php
  lang/en/pagination.php
  lang/en/passwords.php
  lang/en/validation-inline.php
  lang/en/validation.php
  lang/eo.json
  lang/es.json
  lang/fr.json
  lang/fr/auth.php
  lang/fr/pagination.php
  lang/fr/passwords.php
  lang/fr/validation-inline.php
  lang/fr/validation.php
  lang/it.json
  lang/nb_NO.json
  lang/nl.json
  lang/nl/auth.php
  lang/nl/pagination.php
  lang/nl/passwords.php
  lang/nl/validation-inline.php
  lang/nl/validation.php
  lang/pl.json
  lang/pl/auth.php
  lang/pl/pagination.php
  lang/pl/passwords.php
  lang/pl/validation-inline.php
  lang/pl/validation.php
  lang/sv.json
  lang/sv/auth.php
  lang/sv/pagination.php
  lang/sv/passwords.php
  lang/sv/validation-inline.php
  lang/sv/validation.php
  lang/tr.json
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/layouts/app.blade.php
  resources/vue/components/CheckinInterface.vue
  resources/vue/components/CheckinSuccessHelper.vue
  resources/vue/components/FullScreenModal.vue
  resources/vue/components/ModalComponent.vue
  resources/vue/components/NotificationBell.vue
  resources/vue/components/NotificationList.vue
  resources/vue/components/StationAutocomplete.vue
  resources/vue/components/Stationboard.vue
  vite.config.ts
Labels: Follow merge sequence!

#2115 📝 Correct success response on notifications
  app/Http/Controllers/API/v1/NotificationsController.php
  resources/js/api/api.js
  resources/vue/components/NotificationList.vue
  storage/api-docs/api-docs.json
Labels: Follow merge sequence!
