Repository Traewelling/traewelling, pull requests merged in 2023-10, with the labels that each got.

#1963 :bug: Add display_timezone to config for better timezone handling
  app/Helpers/Helper.php
  config/app.php
Labels: timezoning is hard

#1965 :bug: Only check for timezone offset, if the stop is not cancelled
  app/Helpers/Helper.php
  resources/views/stationboard.blade.php
  tests/Unit/HelperMethodTest.php
Labels: timezoning is hard

#1961 ✨ Add endpoint to fetch tags for multiple statuses
  app/Http/Controllers/API/v1/StatusTagController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: enhancement, APIv1

#1983 🩺🐛 Fix job queue counts
  .idea/trwl.iml
  app/Providers/PrometheusServiceProvider.php
  tests/Unit/Providers/PrometheusServiceProviderTest.php
Labels: bug

#1985 :bug: Add timezone to trip creation
  app/Http/Controllers/Frontend/Admin/TripController.php
  resources/views/admin/trip/create.blade.php
Labels: timezoning is hard
